# Database Related Properties
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order-service?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true


server:
  port: 0
