spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:root@127.0.0.1:27017/talci?authSource=admin

server:
  port: 0

#Discovery
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
